#!/bin/sh

readonly OPENSCAD="/Applications/OpenSCAD.app/Contents/MacOS/OpenSCAD"

action="$1"
filename="$2"
GREATER_THAN="-gt"
rm -f test/*.stl

if [ $# $GREATER_THAN 2 ]
then
  if [ $1 == "start" ]
  then
    echo "usage: openscad_cli start filename (without extension)"
  else
    echo "usage: openscad_cli _command_ (without params)"
  fi
fi

# $# is number of params remaining in the list
# the first [ is an alias for the command test, the second ] is just pretty
# shift moves to the next parameter. Lone paren is for real.
while [ $# $GREATER_THAN 0 ]; do
  case "$1" in
    start)
      export OSCLI_ACTIVE_FILE=$1
    ;;
    test)
    ;;
    render)
      "$OPENSCAD" -o "$2.stl" "$2.scad"
      echo "YUP"
    ;;
    print)
    ;;
  esac
  shift
done
